### ISSUE TITLE
Respawning after dying as doggo issues

### ISSUE THREAD

**Issue by Wafelowski** [NutInc/BetterDoggie#2]
After dying as 939 all his stats will be assigned to you apart from HP/AHP, this means that you spawn with configured scale and boost.
In addition, you also get teleported to the void and you can't be spectated unless you teleport back to any room/surface.

**Comment by Parkeymon** [comment]
Ok ill look into this. Im assuming this is an issue with the 5.0.0 version as its pretty much 100% untested

**Comment by Parkeymon** [comment]
I fixed the issue with size. I wasnt able to recreate the void issue, make another issue if its still a problem.
